Add support for PHP 8 drop support for PHP 7.1 and lower
CycloneDX/cyclonedx-php-composer pull request #17
Opened 2021-02-09 16:50 UTC by Rafalsky

2021-02-13 20:11 UTC, jkowalleck requested changes

2021-02-13 20:11 UTC, jkowalleck commented on .github/workflows/php.yml
> +        php-versions: ["7.1", "7.2", "7.3"]
could you add a test for php7.4 and php8.0 ?

2021-02-15 22:58 UTC, jkowalleck commented
hello @Rafalsky 

Thank you for the pull request, very much appreciated.

One slight remark: 
you removed php<7.1 from the github action. 
could you add php >7.3 to the github action in return?

2021-02-19 16:48 UTC, Rafalsky commented
@jkowalleck Updated as requested.

2021-03-05 08:02 UTC, jkowalleck approved these changes

2021-03-05 08:23 UTC, jkowalleck commented
@coderpatros 

i'd love to have this PR merged to master
we could release it as 1.3, since it does not include breaking changes in the interfaces CLI nor method calls.

what do you think?

----

It's common practice in the PHP SemVer world, to have minor versions that change the minimum requirements(`composer.json`)
Impact on the users: composer will automatically download compatible version suitable to the runtime environment, according to the users decision in thier `composer.json`.

see prominent examples introducing php8 support:
* phpunit:  via [9.3](https://packagist.org/packages/phpunit/phpunit#9.3.0)
  by changing from `php: ^7.3` to `php: ^7.3 || ^8.0`
* symfony: via [5.1.0](https://packagist.org/packages/symfony/framework-bundle#v5.0.9)
  by changing from `php: ^7.2.5` to `php: >=7.2.5`
* laravel: via [8.12.0](https://packagist.org/packages/laravel/framework#v8.12.0)
  by changing from `php: ^7.3` to `php: ^7.3 | ^8.0`

2021-03-05 10:04 UTC, coderpatros commented
@jkowalleck I think if we are dropping support for a minor version of PHP we should probably treat that as a major version bump.

2021-03-05 15:02 UTC, jkowalleck commented
@coderpatros  i see.

thanks again, @Rafalsky .
your changes will be in the upcoming 2.0 release, then.

2021-03-06 09:43 UTC, merged